config/routes.rb
CustomerAddresses::Application.routes.draw do
  
  root :to=> "customers#index"
  
  resources :addresses
  resources :customers

end

app/models/address.rb
class Address < ActiveRecord::Base
  
  attr_accessible :city, :country, :customer_id, :line_1, :line_2
  belongs_to :customer
  
  validates  :city, :country, :customer_id, :line_1, :line_2, :presence => true  
  
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  
  attr_accessible :date_became_customer, :email, :name, :addresses_attributes
  
  has_many :addresses
  
  accepts_nested_attributes_for :addresses,                                
                                  :reject_if => lambda { |attrs| attrs.all? { |key, value| value.blank? } },
                                  :allow_destroy => true
  
  validates :name, :email, :date_became_customer , :presence => true  
    
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @addresses }
    end
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
    @address = Address.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/new
  # GET /addresses/new.json
  def new
    @address = Address.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/1/edit
  def edit
    @address = Address.find(params[:id])
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(params[:address])

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render json: @address, status: :created, location: @address }
      else
        format.html { render action: "new" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /addresses/1
  # PUT /addresses/1.json
  def update
    @address = Address.find(params[:id])

    respond_to do |format|
      if @address.update_attributes(params[:address])
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address = Address.find(params[:id])
    @address.destroy

    respond_to do |format|
      format.html { redirect_to addresses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  def index
        add_breadcrumb "Customer", customers_path
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])
    
    add_breadcrumb "Customer", customers_path
    add_breadcrumb @customer.name , customer_path(@customer)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def link_to_remove_fields(name, f, options = {})
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)", options)
  end

  def link_to_add_fields(name, f, association, options = {})
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{ association }", :onsubmit => "return $(this.)validate();") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end

    link_to_function(name, "add_fields(this, \"#{ association }\", \"#{ escape_javascript(fields) }\")", options)
  end
  
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %><br />
    <%= f.number_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :line_1 %><br />
    <%= f.text_field :line_1 %>
  </div>
  <div class="field">
    <%= f.label :line_2 %><br />
    <%= f.text_field :line_2 %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<h1>Listing addresses</h1>

<table>
  <tr>
    <th>Customer</th>
    <th>Line 1</th>
    <th>Line 2</th>
    <th>Country</th>
    <th>City</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @addresses.each do |address| %>
  <tr>
    <td><%= address.customer_id %></td>
    <td><%= address.line_1 %></td>
    <td><%= address.line_2 %></td>
    <td><%= address.country %></td>
    <td><%= address.city %></td>
    <td><%= link_to 'Show', address %></td>
    <td><%= link_to 'Edit', edit_address_path(address) %></td>
    <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Customer:</b>
  <%= @address.customer_id %>
</p>

<p>
  <b>Line 1:</b>
  <%= @address.line_1 %>
</p>

<p>
  <b>Line 2:</b>
  <%= @address.line_2 %>
</p>

<p>
  <b>Country:</b>
  <%= @address.country %>
</p>

<p>
  <b>City:</b>
  <%= @address.city %>
</p>


<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

app/views/customers/_address_fields.html.erb
<div id="new-address-fields" class="modal fade" data-backdrop="static">
  
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>New Address</h3>
  </div>
  
  <div class="modal-body">
    
    <fieldset>
      
      <div class="control-group">
        <%= f.label("Line1:", :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:line_1, :class => "input-xlarge field", :data => { :validation => "required validate_max_length length150", "validation-error-msg" =>"Address Line 1 is required and cannot be longer than 150 characters."}) %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label("Line2:", :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:line_2, :class => "input-xlarge field", :data => { :validation => "required validate_max_length length150", "validation-error-msg" =>"Address Line 2 is required and cannot be longer than 150 characters."}) %>
        </div>
      </div>
      
      
      <div class="control-group">
        <%= f.label("City:", :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:city, :class => "input-xlarge field text-center", :data => { :validation => "required validate_max_length length50", "validation-error-msg" =>"City is required and cannot be longer than 50 characters."}) %>
        </div>
      </div>
      
      
      <div class="control-group">
        <%= f.label("Country:", :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:country, :class => "input-xlarge field text-center", :data => { :validation => "required validate_max_length length50", "validation-error-msg" =>"Country is required and cannot be longer than 50 characters."}) %>
        </div>
      </div>
      
      <%= f.hidden_field(:_destroy, :class => "field") %>
      
    </fieldset>
    
  </div>
  
  <div class="modal-footer">
    <button id="addButton" type="button" class="btn btn-primary" data-dismiss="modal" aria-hidden="true" title="Add this address to the list of addresss that are assigned to this Ship.">Save</button>
    <button id="cancelButton" type="button" class="btn btn-inverse" data-dismiss="modal" aria-hidden="true" title="Close this screen without adding the address to the list.">Close</button>
  </div>
  
</div>

<script type="text/javascript">
  addressFieldsUI.init();
</script>

app/views/customers/_addresses_table.html.erb
<table id="addresses-table" class="table table-hover table-striped">

  <thead>
    
    <th>#</th>
    <th>Address Line 1</th>
    <th>Address Line 2</th>
    <th>City</th>
    <th>Country</th>
    <th></th>
    
  </thead>
  
  <tbody>
    
    <%= f.fields_for(:addresses) do |addresses_form| %>
    
    <tr class="fields">
    
      <td><%= addresses_form.text_field(:id, :class=>"span1 text-center", :disabled=> true)  %></td>
      <td><%= addresses_form.text_field(:line_1,:class=>"span3") %></td>
      <td><%= addresses_form.text_field(:line_2,:class=>"span3") %></td>
      <td><%= addresses_form.text_field(:city,:class=>"span2") %></td>
      <td><%= addresses_form.text_field(:country,:class=>"span2") %></td>
      
      <td>
        <%= link_to_remove_fields('<strong>X</strong>'.html_safe , addresses_form , :title => "Delete this address.") %>
      </td>
    
    </tr>
    
    <% end %>
    
  </tbody>
</table>

app/views/customers/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error alert-block">
        The form contains <%= pluralize(object.errors.count, "error") %>.
        <ul>
          <% object.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
<% end %>

app/views/customers/_form.html.erb
<%= form_for(@customer, :html => {:class => "form form-horizontal" }, :validate=> false) do |f| %>

<fieldset>
  
   <%= render('error_messages', :object => f.object ) %>
   
  <div class="control-group">
    <%= f.label "Name:", :class => 'control-label' %>
    <div class="controls">      
      <%= f.text_field :name, :class => 'field' %>          
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label "Email:", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' , :error_message=> false %>         
    </div>
  </div>
    
  <div class="control-group">
    <%= f.label  "Started At:", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :date_became_customer, :class => 'text_field text-center' %>         
    </div>
  </div>

  
</fieldset>
       
<hr/>
       
    <fieldset>
       <legend>Addresses</legend>
       <%= render('addresses_table', :f => f) %>
       <%= link_to_add_fields("New Address", f, :addresses, :class => "btn btn-primary", :title => "Add a new Address to the list of Addresses.") %>
       <p></p>
     </fieldset>
   
     <div class="modal-footer">
     
    <%= f.submit("Save", :class => "btn btn-primary", :title => "save") %>
    
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), customers_path, :class => 'btn' %>
    
  </div>

                     
<% end %>

app/views/customers/edit.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1>Editing customer</h1>
</div>

<%= render 'form' %>

app/views/customers/index.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>


<table class="table table-striped">
  <thead>  
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Started date</th>
    <th>Actions</th>
  </tr>
</thead>  
 <tbody>  
<% @customers.each do |customer| %>
  <tr>
    <td><%= customer.name %></td>
    <td><%= mail_to customer.email , customer.email%></td>
    <td><%= customer.date_became_customer %></td>
    
    <td>
        <%= link_to 'Show', customer , :class => 'btn btn-mini btn-primary'%>
        <%= link_to 'Edit', edit_customer_path(customer) , :class => 'btn btn-mini'%>
        <%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } , :class => 'btn btn-mini btn-danger'%>
    </td>
    
  </tr>
<% end %>
 </tbody>  
</table>

<br />

<%= link_to 'New Customer', new_customer_path , :class=> "btn btn-large" %>

app/views/customers/new.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1>New customer</h1>
</div>

<%= render 'form' %>

app/views/customers/show.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @customer.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= mail_to @customer.email , @customer.email %></dd>
  <dt><strong>Started at:</strong></dt>
  <dd><%= @customer.date_became_customer %></dd>
</dl>



<dl class="dl-horizontal">
   <legend>Addresses</legend>
   
   
   
   <table id="addresses-table" class="table table-hover table-striped">

     <thead>
    
       <th>#</th>
       <th>Address Line 1</th>
       <th>Address Line 2</th>
       <th>City</th>
       <th>Country</th>
    
     </thead>
  
     <tbody>
    
       <%@customer.addresses.each do |addresse| %>
    
       <tr class="fields">
    
         <td><%= addresse.id  %></td>
         <td><%= addresse.line_1%></td>
          <td><%= addresse.line_2%></td>
          <td><%= addresse.city%></td>
          <td><%= addresse.country%></td>
          
       </tr>
    
       <% end %>
    
     </tbody>
   </table>
   
     
</dl>
 

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              customers_path, :class => 'btn' %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_customer_path(@customer), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              customer_path(@customer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Customer Addresses" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li> <a href="/">Home</a></li>
              <li><a href="/customers"><i class="icon-th-list"></i> Customers</a></li>
              <li><a href="/customers/new"><i class="icon-user"></i> New customer</a></li>              
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      
      <div class="row">
        <div class="messages span9">
          <%= bootstrap_flash %>
        </div>
      </div>
              
      <div class="row">
        <br/>
        <%= render_breadcrumbs %>
        <%= yield %>
      </div>
              
    </div>
        
    <footer class="footer">
      <div class="container">
        <p class="pull-right"><a href="#">top</a></p>
        <p>&copy; msolutions 2013</p>
        <ul class="footer-links">
          
        </ul>
      </div>
    </footer>

  </div> <!-- /container -->

  <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
  </html>